// Generated by scripts/migrate-blog.py. Article bodies stay on the server.
import 'server-only';
import post0 from '@/content/blog/posts/boston-international-credential-evaluation-services.json';
import post1 from '@/content/blog/posts/fastest-uscis-ready-credential-evaluation-services-2026.json';
import post2 from '@/content/blog/posts/los-angeles-foreign-credential-evaluation-services.json';
import post3 from '@/content/blog/posts/los-angeles-international-credential-evaluation-services.json';
import post4 from '@/content/blog/posts/miami-international-credential-evaluation-services.json';
import post5 from '@/content/blog/posts/new-york-foreign-credential-evaluation-services.json';
import post6 from '@/content/blog/posts/new-york-international-credential-evaluation-services.json';
import post7 from '@/content/blog/posts/san-francisco-foreign-credential-evaluation-services.json';
import post8 from '@/content/blog/posts/san-francisco-international-credential-evaluation-services.json';
import post9 from '@/content/blog/posts/california-barbercosmo-credential-evaluation-and-translations.json';
import post10 from '@/content/blog/posts/california-best-education-credential-evaluation-services.json';
import post11 from '@/content/blog/posts/credential-evaluation-for-education.json';
import post12 from '@/content/blog/posts/education-evaluation-h1b-for-india.json';
import post13 from '@/content/blog/posts/foreign-credential-evaluation-in-usa-China.json';
import post14 from '@/content/blog/posts/foreign-credential-evaluation-in-usa-csec.json';
import post15 from '@/content/blog/posts/foreign-credential-evaluation-in-usa-latin-america.json';
import post16 from '@/content/blog/posts/georgia-best-education-credential-evaluation-agencies.json';
import post17 from '@/content/blog/posts/illinois-credential-evaluation-and-translations.json';
import post18 from '@/content/blog/posts/los-angeles-best-education-credential-evaluation-agencies.json';
import post19 from '@/content/blog/posts/los-angeles-credential-evaluation-and-translations.json';
import post20 from '@/content/blog/posts/miami-credential-evaluation-and-translations.json';
import post21 from '@/content/blog/posts/miami-foreign-credential-evaluation-services.json';
import post22 from '@/content/blog/posts/Pakistani-degree-equivalency-in-USA.json';
import post23 from '@/content/blog/posts/san-francisco-best-education-credential-evaluation-agencies.json';
import post24 from '@/content/blog/posts/san-francisco-credential-evaluation-and-translations.json';
import post25 from '@/content/blog/posts/best-credential-evaluation-services.json';
import post26 from '@/content/blog/posts/e-credential-evaluation-for-uscis.json';
import post27 from '@/content/blog/posts/ata-certified-translation-services.json';
import post28 from '@/content/blog/posts/boston-affordable-cheap-translation-services.json';
import post29 from '@/content/blog/posts/boston-ata-certified-translation-and-interpretation.json';
import post30 from '@/content/blog/posts/boston-best-certified-translation-services-companies.json';
import post31 from '@/content/blog/posts/boston-certified-and-notarized-translation-services.json';
import post32 from '@/content/blog/posts/boston-certified-chinese-translation-service.json';
import post33 from '@/content/blog/posts/boston-certified-spanish-translation-services.json';
import post34 from '@/content/blog/posts/boston-foreign-language-interpreter-agency.json';
import post35 from '@/content/blog/posts/boston-interpreting-agencies-companies.json';
import post36 from '@/content/blog/posts/boston-professional-translation-services-agency.json';
import post37 from '@/content/blog/posts/boston-technical-translation-services-company.json';
import post38 from '@/content/blog/posts/boston-top-certified-translation-companies.json';
import post39 from '@/content/blog/posts/boston-uscis-certified-translation-services.json';
import post40 from '@/content/blog/posts/h1b-expert-opinion-letters.json';
import post41 from '@/content/blog/posts/how-to-find-translation-services-online.json';
import post42 from '@/content/blog/posts/los-angeles-affordable-cheap-translation-services.json';
import post43 from '@/content/blog/posts/los-angeles-ata-certified-translation-and-interpretation.json';
import post44 from '@/content/blog/posts/los-angeles-best-certified-translation-services-companies.json';
import post45 from '@/content/blog/posts/los-angeles-certified-and-notorized-translation.json';
import post46 from '@/content/blog/posts/los-angeles-certified-chinese-translation-service.json';
import post47 from '@/content/blog/posts/los-angeles-certified-spanish-translation-services.json';
import post48 from '@/content/blog/posts/los-angeles-foreign-language-interpreter-agency.json';
import post49 from '@/content/blog/posts/los-angeles-uscis-certified-translation-services.json';
import post50 from '@/content/blog/posts/miami-affordable-cheap-translation-services.json';
import post51 from '@/content/blog/posts/miami-ata-certified-translation-and-interpretation.json';
import post52 from '@/content/blog/posts/miami-certified-and-notorized-translation.json';
import post53 from '@/content/blog/posts/miami-certified-chinese-translation-service.json';
import post54 from '@/content/blog/posts/miami-certified-spanish-translation-services.json';
import post55 from '@/content/blog/posts/miami-interpreting-agencies-companies.json';
import post56 from '@/content/blog/posts/miami-language-translation-services.json';
import post57 from '@/content/blog/posts/miami-uscis-certified-translation-services.json';
import post58 from '@/content/blog/posts/new-york-affordable-cheap-translation-services.json';
import post59 from '@/content/blog/posts/new-york-ata-certified-translation-and-interpretation.json';
import post60 from '@/content/blog/posts/new-york-best-certified-translation-services-companies.json';
import post61 from '@/content/blog/posts/new-york-certified-and-notarized-translation-services.json';
import post62 from '@/content/blog/posts/new-york-certified-chinese-translation-service.json';
import post63 from '@/content/blog/posts/new-york-certified-spanish-translation-services.json';
import post64 from '@/content/blog/posts/new-york-foreign-language-interpreter-agency.json';
import post65 from '@/content/blog/posts/new-york-interpreting-agencies-companies.json';
import post66 from '@/content/blog/posts/new-york-professional-translation-services-agency.json';
import post67 from '@/content/blog/posts/new-york-technical-translation-services-company.json';
import post68 from '@/content/blog/posts/new-york-uscis-certified-translation-services.json';
import post69 from '@/content/blog/posts/san-francisco-affordable-cheap-translation-services.json';
import post70 from '@/content/blog/posts/san-francisco-ata-certified-translation-and-interpretation.json';
import post71 from '@/content/blog/posts/san-francisco-certified-chinese-translation-service.json';
import post72 from '@/content/blog/posts/san-francisco-certified-spanish-translation-services.json';
import post73 from '@/content/blog/posts/san-francisco-interpreting-agencies-companies.json';
import post74 from '@/content/blog/posts/san-francisco-professional-translation-services-agency.json';
import post75 from '@/content/blog/posts/san-francisco-uscis-certified-translation-services.json';
import post76 from '@/content/blog/posts/san-fransico-certified-and-notorized-translation.json';
import post77 from '@/content/blog/posts/e-aet-expert-opinion-letter.json';
import post78 from '@/content/blog/posts/eb-2-niw-expert-opinion-letters.json';

export type MigratedPost = { slug: string; title: string; description: string; toc: { id: string; title: string }[]; html: string };
export const blogPosts: Record<string, MigratedPost> = {
  'boston-international-credential-evaluation-services': post0,
  'fastest-uscis-ready-credential-evaluation-services-2026': post1,
  'los-angeles-foreign-credential-evaluation-services': post2,
  'los-angeles-international-credential-evaluation-services': post3,
  'miami-international-credential-evaluation-services': post4,
  'new-york-foreign-credential-evaluation-services': post5,
  'new-york-international-credential-evaluation-services': post6,
  'san-francisco-foreign-credential-evaluation-services': post7,
  'san-francisco-international-credential-evaluation-services': post8,
  'california-barbercosmo-credential-evaluation-and-translations': post9,
  'california-best-education-credential-evaluation-services': post10,
  'credential-evaluation-for-education': post11,
  'education-evaluation-h1b-for-india': post12,
  'foreign-credential-evaluation-in-usa-China': post13,
  'foreign-credential-evaluation-in-usa-csec': post14,
  'foreign-credential-evaluation-in-usa-latin-america': post15,
  'georgia-best-education-credential-evaluation-agencies': post16,
  'illinois-credential-evaluation-and-translations': post17,
  'los-angeles-best-education-credential-evaluation-agencies': post18,
  'los-angeles-credential-evaluation-and-translations': post19,
  'miami-credential-evaluation-and-translations': post20,
  'miami-foreign-credential-evaluation-services': post21,
  'Pakistani-degree-equivalency-in-USA': post22,
  'san-francisco-best-education-credential-evaluation-agencies': post23,
  'san-francisco-credential-evaluation-and-translations': post24,
  'best-credential-evaluation-services': post25,
  'e-credential-evaluation-for-uscis': post26,
  'ata-certified-translation-services': post27,
  'boston-affordable-cheap-translation-services': post28,
  'boston-ata-certified-translation-and-interpretation': post29,
  'boston-best-certified-translation-services-companies': post30,
  'boston-certified-and-notarized-translation-services': post31,
  'boston-certified-chinese-translation-service': post32,
  'boston-certified-spanish-translation-services': post33,
  'boston-foreign-language-interpreter-agency': post34,
  'boston-interpreting-agencies-companies': post35,
  'boston-professional-translation-services-agency': post36,
  'boston-technical-translation-services-company': post37,
  'boston-top-certified-translation-companies': post38,
  'boston-uscis-certified-translation-services': post39,
  'h1b-expert-opinion-letters': post40,
  'how-to-find-translation-services-online': post41,
  'los-angeles-affordable-cheap-translation-services': post42,
  'los-angeles-ata-certified-translation-and-interpretation': post43,
  'los-angeles-best-certified-translation-services-companies': post44,
  'los-angeles-certified-and-notorized-translation': post45,
  'los-angeles-certified-chinese-translation-service': post46,
  'los-angeles-certified-spanish-translation-services': post47,
  'los-angeles-foreign-language-interpreter-agency': post48,
  'los-angeles-uscis-certified-translation-services': post49,
  'miami-affordable-cheap-translation-services': post50,
  'miami-ata-certified-translation-and-interpretation': post51,
  'miami-certified-and-notorized-translation': post52,
  'miami-certified-chinese-translation-service': post53,
  'miami-certified-spanish-translation-services': post54,
  'miami-interpreting-agencies-companies': post55,
  'miami-language-translation-services': post56,
  'miami-uscis-certified-translation-services': post57,
  'new-york-affordable-cheap-translation-services': post58,
  'new-york-ata-certified-translation-and-interpretation': post59,
  'new-york-best-certified-translation-services-companies': post60,
  'new-york-certified-and-notarized-translation-services': post61,
  'new-york-certified-chinese-translation-service': post62,
  'new-york-certified-spanish-translation-services': post63,
  'new-york-foreign-language-interpreter-agency': post64,
  'new-york-interpreting-agencies-companies': post65,
  'new-york-professional-translation-services-agency': post66,
  'new-york-technical-translation-services-company': post67,
  'new-york-uscis-certified-translation-services': post68,
  'san-francisco-affordable-cheap-translation-services': post69,
  'san-francisco-ata-certified-translation-and-interpretation': post70,
  'san-francisco-certified-chinese-translation-service': post71,
  'san-francisco-certified-spanish-translation-services': post72,
  'san-francisco-interpreting-agencies-companies': post73,
  'san-francisco-professional-translation-services-agency': post74,
  'san-francisco-uscis-certified-translation-services': post75,
  'san-fransico-certified-and-notorized-translation': post76,
  'e-aet-expert-opinion-letter': post77,
  'eb-2-niw-expert-opinion-letters': post78,
};
